from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd + '/../../include']
group   = []

if not GetDepend(['RT_USING_SERIAL_8250']):
    Return('group')

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
