from building import *

group = []

if not GetDepend(['RT_USING_IOMMU']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['iommu.c']

if GetDepend(['RT_IOMMU_SMMUV3']):
    src += ['iommu-smmu-v3.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
