from building import *

group = []

if not GetDepend(['RT_USING_PM']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['pm.c', 'lptimer.c']

if GetDepend(['RT_PM_RESET_SYSCON_POWEROFF']):
    src += ['pm-syscon-poweroff.c']

if GetDepend(['RT_PM_RESET_SYSCON']):
    src += ['pm-syscon-reboot.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
