from building import *

group = []
objs = []

if not GetDepend(['RT_USING_THERMAL']):
    Return('group')

cwd = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = [cwd + '/../include']

src = ['thermal.c']

if GetDepend(['RT_THERMAL_BCM2711']):
    src += ['thermal-bcm2711.c']

if GetDepend(['RT_THERMAL_BCM2835']):
    src += ['thermal-bcm2835.c']

if GetDepend(['RT_THERMAL_ROCKCHIP_TSADC']):
    src += ['thermal-rockchip_tsadc.c']

if GetDepend(['RT_THERMAL_COOL_PWM_FAN']):
    src += ['thermal-cool-pwm-fan.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
