from building import *

cwd = GetCurrentDir()
src = ['device.c', 'driver.c']
CPPPATH = [cwd + '/../include']
group = []

if GetDepend(['RT_USING_DM']):
    src += ['dm.c', 'bus.c', 'platform.c']

src += ['device.c']
src += ['driver.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

