from building import *

group   = []

if not GetDepend(['RT_SOC_BROADCOM']):
    Return('group')

cwd     = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src     = []

if GetDepend(['RT_SOC_BROADCOM_RASPBERRYPI_VOLTAGE_MONITOR']):
    src += ['raspberrypi-voltage-monitor.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)
Return('group')
