from building import *

group = []

if not GetDepend(['RT_USING_RESET']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['reset.c']

if GetDepend(['RT_RESET_BRCMSTB_RESCAL']):
    src += ['reset-brcmstb-rescal.c']

if GetDepend(['RT_RESET_BRCMSTB']):
    src += ['reset-brcmstb.c']

if GetDepend(['RT_RESET_RASPBERRYPI']):
    src += ['reset-raspberrypi.c']

if GetDepend(['RT_RESET_SCMI']):
    src += ['reset-scmi.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
