from building import *

group = []

if not GetDepend(['RT_INPUT_KEYBOARD']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = []

if GetDepend(['RT_INPUT_KEYBOARD_ADC_KEYS']):
    src += ['adc-keys.c']

if GetDepend(['RT_INPUT_KEYBOARD_GPIO_KEYS']):
    src += ['gpio-keys.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
