from building import *

group = []

if not GetDepend(['RT_USING_DM']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = []

if GetDepend(['RT_PMDOMAIN_BCM2835']):
    src += ['pm-domain-bcm2835.c']

if GetDepend(['RT_PMDOMAIN_RASPBERRYPI']):
    src += ['pm-domain-raspberrypi.c']

if GetDepend(['RT_PMDOMAIN_ROCKCHIP']):
    src += ['pm-domain-rockchip.c']

if GetDepend(['RT_PMDOMAIN_SCMI']):
    src += ['pm-domain-scmi.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
