from building import *

group = []

if not GetDepend(['RT_ETHERNET_REALTEK']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = []

# if GetDepend(['RT_REALTEK_PTP']):
#     src += ['r8125_ptp.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
