from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']
group = []
objs = []
src = []

if not GetDepend(['RT_USING_SERIAL']):
    Return('group')

if GetDepend(['RT_USING_SMART']):
    src += Glob('serial_tty.c')

if GetDepend(['RT_USING_SERIAL_V2']):
    src += ['dev_serial_v2.c']
else:
    src += ['dev_serial.c']

if GetDepend(['RT_USING_SERIAL_BYPASS']):
    src += ['bypass.c']

if GetDepend(['RT_USING_DM']):
    src += ['serial_dm.c']

    list = os.listdir(cwd)

    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH) + objs

Return('group')
