from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd + '/../../include']

group = DefineGroup('DeviceDrivers', src, depend = ['RT_SOC_CHIP_MEDIA_JPU'], CPPPATH = CPPPATH)

Return('group')
