from building import *

group = []

if not GetDepend(['RT_INPUT_TOUCHSCREEN']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../../include']

src = []

if GetDepend(['RT_INPUT_TOUCHSCREEN_RASPBERRYPI_FW']):
    src += ['raspberrypi-ts.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
